# fly.toml app configuration file generated for discord-zip on 2024-08-24T18:04:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-zip'
primary_region = 'nrt'

[build]

[[vm]]
  size = 'shared-cpu-1x'
